
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: Build all hosts
  image: nixos/nix
  commands:
  - nix-env -i git
  - nix-build krops.nix -A all
  - ls -al
