kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: Show flake info
  # image: nixos/nix
  image: nixpkgs/nix-flakes
  commands:
  - nix --experimental-features nix-command flake show
  - nix --experimental-features nix-command flake info
  - nix --experimental-features nix-command flake list-inputs
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Build all hosts
  image: nixpkgs/nix-flakes
  commands:
  - nix-build krops.nix -A all
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

---
kind: pipeline
type: docker
name: update flakes

steps:
- name: Update flake.lock
  image: nixpkgs/nix-flakes
  commands:
  - date

trigger:
  event:
  - cron
  cron:
  - hourly
