
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: Build all hosts
  # image: nixos/nix
  image: nixpkgs/nix-flakes
  commands:
  - nix-env -i git
  - nix-build krops.nix -A all
  - "sh <(curl -L https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200804_ed52cf6/install)"
  - ls -al
