
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: Build all hosts
  # image: nixos/nix
  image: nixpkgs/nix-flakes
  commands:
  - nix build krops.nix -A all
  - ls -al
  environment:
    #NIX_PATH: nixpkgs=channel:nixos-unstable
